[package]
name = "stress-majorization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utility = { path = "../utility" }
macroquad = "0.3.24"
petgraph = "0.6.2"