[package]
name = "render-targets-be-like"
version = "0.1.0"
authors = ["profan <robinhubner@gmail.com>"]
edition = "2021"

[dependencies]
macroquad = "0.4.6"

[profile.dev]
incremental = true
opt-level = 2