[package]
name = "multi-rymd"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.3.24"
lockstep = { path = "../lockstep" }
lockstep-client = { path = "../lockstep/client" }
utility = { path = "../utility" }
deterministic-hash = "1.0.1"
nanoserde = "0.1.35"

[profile.dev]
incremental = true
opt-level = 2