[package]
name = "polar"
version = "0.1.0"
authors = ["profan <robinhubner@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.24"