[package]
name = "territory"
version = "0.1.0"
authors = ["profan <robinhubner@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utility = { path = "../utility" }
macroquad = "0.3.24"
noise = "0.8.1"