[package]
name = "lockstep-server"
version = "0.1.0"
edition = "2021"

[dependencies]
nanoserde = "0.1.35"
deterministic-hash = "1.0.1"
lockstep = { path = "../" }
ws = "0.9.2"

[profile.dev]
incremental = true
opt-level = 2